### ISSUE TITLE
Reopening saved box is hard UX-wise

### ISSUE THREAD

**Issue by WofWca** [Raais/noteguard#1]
After I lock the box, I return to the Authenticate screen. It is not clear there that I am supposed to enter the key first.
I tried opening the box, but I just get an error in the console. Only after a while I figured that I'm supposed to import the key first, and when that is done, click on "Open .box" to get back to editing where I left off.

**Comment by Raais** [comment]
Agree, its not intuitive. Let me know if you have suggestions.
